name: Pull Request Target PoC

on:
  pull_request_target:
    types: [opened, synchronize]

  pull_request:
    types: [opened, synchronize]

env:
  SOURCE_IS_FORK: ${{ github.event.pull_request.head.repo.fork }}
  RUN_ON_MAIN: ${{ github.event_name == 'pull_request_target' }}

jobs:
  trigger_branch_creation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Branch Creation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          FORK_REPO=${{ github.event.pull_request.head.repo.clone_url }}
          FORK_BRANCH=${{ github.event.pull_request.head.ref }}
          FORK_OWNER=${{ github.event.pull_request.head.repo.owner.login }}

          echo "Triggering backup branch creation with the following details:"
          echo "PR_NUMBER: $PR_NUMBER"
          echo "FORK_REPO: $FORK_REPO"
          echo "FORK_BRANCH: $FORK_BRANCH"
          echo "FORK_OWNER: $FORK_OWNER"

          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d '{"event_type":"backup-branch","client_payload":{"pr_number":'"$PR_NUMBER"',"fork_repo":"'"$FORK_REPO"'","fork_branch":"'"$FORK_BRANCH"'","fork_owner":"'"$FORK_OWNER"'"}}'
